### ISSUE TITLE
Bundling failed due to dependency issue

### ISSUE THREAD

**Issue by Aqueelmiq** [mcabs3/google-places-web#13]
It complains about dependency not found when i try to use your project

```
bundling failed: Error: While trying to resolve module `google-places-web` from file `/Users/aqueelmiqdad/went/src/apis/GooglePlaces.js`, the package `/Users/aqueelmiqdad/went/node_modules/google-places-web/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/aqueelmiqdad/went/node_modules/google-places-web/dist/google-places-web.umd.js`. Indeed, none of these files exist:

  * `/Users/aqueelmiqdad/went/node_modules/google-places-web/dist/google-places-web.umd.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/aqueelmiqdad/went/node_modules/google-places-web/dist/google-places-web.umd.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (/Users/aqueelmiqdad/went/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:15)
    at DependencyGraph.resolveDependency (/Users/aqueelmiqdad/went/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)
    at Object.resolve (/Users/aqueelmiqdad/went/node_modules/metro/src/lib/transformHelpers.js:116:25)
    at dependencies.map.result (/Users/aqueelmiqdad/went/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/aqueelmiqdad/went/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)
    at /Users/aqueelmiqdad/went/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33
    at Generator.next (<anonymous>)
    at step (/Users/aqueelmiqdad/went/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)
    at /Users/aqueelmiqdad/went/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:467
```

**Comment by mcabs3** [comment]
@Aqueelmiq I'm sorry, totally made a rookie mistake after replacing Rollup with Parcel, I updated the package.json and published a new build `0.1.8`, let me know if that resolved your issue. Thanks!
